# Generated by Django 5.0.3 on 2025-07-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_created_at_client_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
