# Generated by Django 5.0.3 on 2025-07-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_measurement_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
