# Generated by Django 5.0.3 on 2025-08-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
    ]
