# Generated by Django 5.0.3 on 2025-08-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_date_payment_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='note',
            new_name='notes',
        ),
    ]
